#!/bin/bash

# Concatenates the source files of the RallySportED-js client into a single distributable file.

DST_DIRECTORY="./client/js/"
DST_FILENAME="rallysported.cat.js"
VERSION="live"

SOURCE_FILES=("./client/js/jszip/jszip.min.js"
		      "./client/js/filesaver/FileSaver.min.js"
		      "./client/js/retro-ngon/rngon.cat.js"
              "./client/js/rallysported/rallysported.js"
              "./client/js/rallysported/project/manifesto.js"
              "./client/js/rallysported/project/project.js"
              "./client/js/rallysported/project/hitable.js"
              "./client/js/rallysported/misc/constants.js"
              "./client/js/rallysported/misc/shared-mode.js"
              "./client/js/rallysported/world/world.js"
              "./client/js/rallysported/world/mesh-builder.js"
              "./client/js/rallysported/world/camera.js"
              "./client/js/rallysported/visual/texture.js"
              "./client/js/rallysported/visual/palette.js"
              "./client/js/rallysported/track/varimaa.js"
              "./client/js/rallysported/track/maasto.js"
              "./client/js/rallysported/track/palat.js"
              "./client/js/rallysported/track/props.js"
              "./client/js/rallysported/ui/ui.js"
              "./client/js/rallysported/ui/popup-notification.js"
              "./client/js/rallysported/ui/font.js"
              "./client/js/rallysported/ui/ground-brush.js"
              "./client/js/rallysported/ui/draw.js"
              "./client/js/rallysported/ui/window.js"
              "./client/js/rallysported/ui/input-state.js"
              "./client/js/rallysported/ui/mouse-picking-element.js"
              "./client/js/rallysported/scene/scene.js"
              "./client/js/rallysported/core/scene-3d.js"
              "./client/js/rallysported/core/scene-tilemap.js"
              "./client/js/rallysported/core/core.js")

echo "// WHAT: Concatenated JavaScript source files" > "$DST_DIRECTORY/$DST_FILENAME"
echo "// PROGRAM: RallySportED-js" >> "$DST_DIRECTORY/$DST_FILENAME"
echo "// AUTHOR: Tarpeeksi Hyvae Soft" >> "$DST_DIRECTORY/$DST_FILENAME"
echo "// VERSION: $VERSION (`LC_ALL=en_US.utf8 date -u +"%d %B %Y %H:%M:%S %Z"`)" >> "$DST_DIRECTORY/$DST_FILENAME"
echo "// LINK: https://www.github.com/leikareipa/rallysported-js/" >> "$DST_DIRECTORY/$DST_FILENAME"
echo "// INCLUDES: { JSZip (c) 2009-2016 Stuart Knightley, David Duponchel, Franz Buchinger, António Afonso }" >> "$DST_DIRECTORY/$DST_FILENAME"
echo "// INCLUDES: { FileSaver.js (c) 2016 Eli Grey }" >> "$DST_DIRECTORY/$DST_FILENAME"
echo "// INCLUDES: { The retro n-gon renderer (c) 2019 Tarpeeksi Hyvae Soft }" >> "$DST_DIRECTORY/$DST_FILENAME"
echo "// FILES:" >> "$DST_DIRECTORY/$DST_FILENAME"
printf "//\t%s\n" "${SOURCE_FILES[@]}" >> "$DST_DIRECTORY/$DST_FILENAME"
echo -e "/////////////////////////////////////////////////\n" >> "$DST_DIRECTORY/$DST_FILENAME"

cat ${SOURCE_FILES[@]} >> "$DST_DIRECTORY/$DST_FILENAME"
